plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'io.github.hyjn.nexori'
version = '2.5.0'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

dependencies {
    api 'com.google.code.gson:gson:2.11.0'
    compileOnlyApi 'com.google.code.findbugs:jsr305:3.0.2'
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
    options.addStringOption('-add-stylesheet', file('src/docs/javadoc/nexori-javadoc.css').absolutePath)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'nexori-api'
        }
    }
}
